-- AlterTable
ALTER TABLE "visit" ADD COLUMN     "profit" DECIMAL(10,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "visit_item" ADD COLUMN     "costPrice" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "profit" DECIMAL(10,2) NOT NULL DEFAULT 0;
